on:
  push:
    branches:
      - develop
      - main

jobs:
  recreate-files-with-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Recreate JSON file
        env:
          SECRET_JSON: ${{ secrets.TK_COOKIES_JSON }}
          JSON_FILENAME: ${{ vars.JSON_FILENAME }}
        run: |
          echo "TK_COOKIES_JSON" > function/$JSON_FILENAME
      - name: Recreate config.toml
        run: |
          echo "SECRET_CONFIG_TOML" | tr -d '\r' > config.toml
        shell: bash
        env:
          SECRET_CONFIG_TOML: ${{ secrets.CONFIG_TOML }}
      - name: Debug config file
        run: cat config.toml